{% set awscrt = "awscrt >=0.19.18,<=0.19.19" %}
{% set colorama = "colorama >=0.2.5,<0.4.7" %}
{% set cryptography = "cryptography >=3.3.2,<=40.0.2" %}
{% set distro = "distro >=1.5.0,<1.9.0" %}
{% set docutils = "docutils >=0.10,<0.20" %}
{% set jmespath = "jmespath >=0.7.1,<1.1.0" %}
{% set prompt_toolkit = "prompt_toolkit >=3.0.24,<3.0.39" %}
{% set python_dateutil = "python-dateutil >=2.1,<=2.8.2" %}
{% set ruamel_yaml = "ruamel.yaml >=0.15.0,<=0.17.21" %}
{% set ruamel_yaml_clib = "ruamel.yaml.clib >=0.2.0,<=0.2.7" %}
{% set urllib3 = "urllib3 >=1.25.4,<1.27" %}
# DOUBLE CHECK THESE FOR EACH NEW RELEASE
# greyskull doesn't seem to update them automatically from upstream
{% set awscrt = "awscrt >=0.19.18,<=0.19.19" %}
{% set colorama = "colorama >=0.2.5,<0.4.7" %}
{% set cryptography = "cryptography >=3.3.2,<=40.0.2" %}
{% set distro = "distro >=1.5.0,<1.9.0" %}
{% set docutils = "docutils >=0.10,<0.20" %}
{% set jmespath = "jmespath >=0.7.1,<1.1.0" %}
{% set prompt_toolkit = "prompt_toolkit >=3.0.24,<3.0.39" %}
{% set python_dateutil = "python-dateutil >=2.1,<=2.8.2" %}
{% set ruamel_yaml = "ruamel.yaml >=0.15.0,<=0.17.21" %}
{% set ruamel_yaml_clib = "ruamel.yaml.clib >=0.2.0,<=0.2.7" %}
{% set urllib3 = "urllib3 >=1.25.4,<1.27" %}
{% set name = "awscli" %}
{% set version = "2.15.27" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

# v2 is not on PyPI https://github.com/aws/aws-cli/issues/6785
source:
  url: https://github.com/aws/aws-cli/archive/{{ version }}.tar.gz
  sha256: 92ed92c27235a21d77be9aeb116a632dc34f11b1bdef4101ee43ca4a7aff738d

build:
  number: 0
  # Build uses pep517 with a custom backend
  # console_scripts entrypoints aren't used, so this can't be noarch
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv  # [not unix]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv && mkdir -p $PREFIX/share/bash-completions/completions && echo complete -C aws_completer aws >$PREFIX/share/bash-completions/completions/aws  # [unix]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    # The autocomplete index step is run on the build host
    - {{ colorama }}                         # [build_platform != target_platform]
    - {{ docutils }}                         # [build_platform != target_platform]
    - {{ cryptography }}                     # [build_platform != target_platform]
    - {{ ruamel_yaml }}                      # [build_platform != target_platform]
    - {{ ruamel_yaml_clib }}                 # [build_platform != target_platform]
    - {{ prompt_toolkit }}                   # [build_platform != target_platform]
    - {{ distro }}                           # [build_platform != target_platform]
    - {{ awscrt }}                           # [build_platform != target_platform]
    - {{ python_dateutil }}                  # [build_platform != target_platform]
    - {{ jmespath }}                         # [build_platform != target_platform]
    - {{ urllib3 }}                          # [build_platform != target_platform]

  host:
    - python
    - flit-core ==3.9.0
    - pip
    # The build process generates the autocomplete index (scripts/gen-ac-index)
    # which requires importing awscli modules, so we need to install all runtime
    # dependencies too. YAML anchors don't support merging lists so we have to
    # duplicate everything :-(
    - {{ colorama }}
    - {{ docutils }}
    - {{ cryptography }}
    - {{ ruamel_yaml }}
    - {{ ruamel_yaml_clib }}
    - {{ prompt_toolkit }}
    - {{ distro }}
    - {{ awscrt }}
    - {{ python_dateutil }}
    - {{ jmespath }}
    - {{ urllib3 }}
    # See https://github.com/aws/aws-cli/issues/7942
    - pyopenssl <23.2

  run:
    - python
    - {{ colorama }}
    - {{ docutils }}
    - {{ cryptography }}
    - {{ ruamel_yaml }}
    - {{ ruamel_yaml_clib }}
    - {{ prompt_toolkit }}
    - {{ distro }}
    - {{ awscrt }}
    - {{ python_dateutil }}
    - {{ jmespath }}
    - {{ urllib3 }}
    # See https://github.com/aws/aws-cli/issues/7942
    - pyopenssl <23.2

test:
  imports:
    # find $CONDA_PREFIX/lib/python3.9/site-packages/awscli/ -type f -name __init__.py | sed -re 's%.+(awscli.*)/__init__.py%- \1%' -re s'%/%.%g' | sort
    # Last updated version 2.11.15
    - awscli
    - awscli.autocomplete
    - awscli.autocomplete.local
    - awscli.autocomplete.serverside
    - awscli.autocomplete.serverside.custom_completers
    - awscli.autocomplete.serverside.custom_completers.ddb
    - awscli.autocomplete.serverside.custom_completers.logs
    - awscli.autoprompt
    - awscli.bcdoc
    - awscli.botocore
    - awscli.botocore.crt
    - awscli.botocore.docs
    - awscli.botocore.docs.bcdoc
    - awscli.botocore.retries
    - awscli.botocore.vendored
    - awscli.botocore.vendored.requests
    - awscli.botocore.vendored.requests.packages
    - awscli.botocore.vendored.requests.packages.urllib3
    - awscli.customizations
    - awscli.customizations.cloudformation
    - awscli.customizations.cloudtrail
    - awscli.customizations.codeartifact
    - awscli.customizations.codedeploy
    - awscli.customizations.configservice
    - awscli.customizations.configure
    - awscli.customizations.datapipeline
    - awscli.customizations.dlm
    - awscli.customizations.dynamodb
    - awscli.customizations.ec2
    - awscli.customizations.ec2instanceconnect
    - awscli.customizations.ecs
    - awscli.customizations.eks
    - awscli.customizations.emr
    - awscli.customizations.emrcontainers
    - awscli.customizations.gamelift
    - awscli.customizations.history
    - awscli.customizations.lightsail
    - awscli.customizations.logs
    - awscli.customizations.s3
    - awscli.customizations.s3.syncstrategy
    - awscli.customizations.servicecatalog
    - awscli.customizations.sso
    - awscli.customizations.wizard
    - awscli.customizations.wizard.ui
    - awscli.s3transfer
  commands:
    - aws --version
    - aws_completer
    # Check autocomplete index exists:
    - python -c "import awscli, os; assert os.stat(os.path.join(os.path.dirname(awscli.__file__), 'data', 'ac.index')).st_size > 1e6"
    - COMP_LINE="aws ec2 describe-inst" aws_completer     # [unix]

about:
  home: https://aws.amazon.com/cli/
  license_file: LICENSE.txt
  license: Apache-2.0
  summary: Universal Command Line Environment for AWS.
  dev_url: https://github.com/aws/aws-cli
  doc_url: https://aws.amazon.com/cli/

extra:
  # awscli=1 is maintained in awscli
  feedstock-name: awscli2
  recipe-maintainers:
    - xhochy
    - tkelman
